#!/bin/sh
#
# Copyright (C) 2013-2015 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

SERVICE="plexmediaserver"

# Enable/disable service
if [ "$(omv_config_get "//services/plexmediaserver/enable")" != "1" ]; then
    exit 0
fi

PLEX_HOME="$(getent passwd plex | cut -d: -f6)"
DB_FOLDER="$(omv_config_get "//services/plexmediaserver/db-folder")"
DB_MNTENTREF="$(omv_config_get "//services/plexmediaserver/mntentref")"
DB_MNTENTDIR=$(xmlstarlet sel -t -m "//system/fstab/mntent[uuid='${DB_MNTENTREF}']" -v dir -b ${OMV_CONFIG_FILE} | xmlstarlet unesc)

if ! getent group plex >/dev/null 2>&1; then
    chown -R plex:nogroup "${PLEX_HOME}"
else
    chown -R plex:plex "${PLEX_HOME}"
fi

if [ "${PLEX_HOME}" != "${DB_FOLDER}" ]; then
    if ! omv_is_mounted "${DB_MNTENTDIR}" ; then
        exit 1
    fi

    invoke-rc.d ${SERVICE} stop || :
    pkill -9 -u `id -u plex` || :

    if [ ! -d "${DB_FOLDER}/Library" ]; then
        usermod -d "${DB_FOLDER}" -m plex
    fi

    # Check current database uid.  If different, chown
    dbid="$(stat -c "%u" "${DB_FOLDER}/Library")"
    userid="$(getent passwd plex | cut -d: -f3)"
    if [ "${dbid}" != "${userid}" ]; then
        echo "Changing to proper owner.  This could take a few minutes."
        if ! getent group plex >/dev/null 2>&1; then
            chown -R plex:nogroup "${DB_FOLDER}"
        else
            chown -R plex:plex "${DB_FOLDER}"
        fi
    fi

    invoke-rc.d ${SERVICE} start
fi

# created for plex uninstall because it fails if it can't remove this directory.
if [ ! -d "/var/lib/plexmediaserver" ]; then
    mkdir -p /var/lib/plexmediaserver
fi
