#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2016 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
	remove)
        ;;

	purge)
		# Remove the configuration data
		omv_config_delete "/config/services/plexmediaserver"
	
	if [ -d /opt/plexcodecs ]; then
		rm -rf /opt/plexcodecs >/dev/null 2>&1
	fi
	
        if [ -d /opt/plexpy ]; then
            deb-systemd-helper disable plexpy >/dev/null || true
            deb-systemd-invoke stop plexpy >/dev/null || true
			rm -f /etc/default/plexpy >/dev/null 2>&1
			rm -Rf /opt/plexpy >/dev/null 2>&1
			rm -f /etc/init.d/plexpy >/dev/null 2>&1
		fi
	;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

	*)
		echo "postrm called with unknown argument '$1'" >&2
		exit 1
	;;
esac

exit 0
