#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2014 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    configure)

        ########################################################################
        #  Update the configuration.
        #   <config>
        #       <services>
        #           <plexmediaserver>
        #               <enable>0</enable>
        #               <db-folder></db-folder>
        #               <mntentref></mntentref>
        #               <showtab>0</showtab>
        #           </plexmediaserver>
        #       </services>
        #   </config>
        ########################################################################

        if omv_config_exists "/config/services/plexmediaserver"; then
            ENABLE="$(omv_config_get "//services/plexmediaserver/enable")"
            MNTENTREF="$(omv_config_get "//services/plexmediaserver/mntentref")"
        else
            ENABLE="0"
            MNTENTREF=""
        fi

        omv_config_delete "/config/services/plexmediaserver"

        PLEX_HOME=$(getent passwd plex | cut -d: -f6)

        echo "Initialize configuration"
        object="<enable>${ENABLE}</enable>"
        object="${object}<db-folder>${PLEX_HOME}</db-folder>"
        object="${object}<mntentref>${MNTENTREF}</mntentref>"
        object="${object}<showtab>0</showtab>"
        omv_config_add_element "/config/services" "plexmediaserver" "${object}" true

        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
